### ISSUE TITLE
Add support for laser

### ISSUE THREAD

**Issue by DragonRock** [DragonRock/slideshow.io#3]
It could be nice that the admin could click on a part of his slide and display a red pixel on the audience slides when he wants to show a specific part of a slide.

**Comment by tforgione** [comment]
What would be really nice is : 

  - that the anchor could allow audience to use the laser (why not a green one ?)
  - enable the anchor / audience to draw on the slides (rather than only showing a point, showing lines)

**Comment by DragonRock** [comment]
This issue was moved to DragonRock/slideshow.io-clean#3
